# Generated by Django 4.1.1 on 2022-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address line 2'),
        ),
    ]
